version: '3.1'

services:

  omnidb:
    build: .
    environment:
      - OMNIDB_USER=root
      - OMNIDB_PASS=root

      - DB_TECH=postgresql
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_USER=root
      - DB_NAME=postgres

    ports:
      - 8080:8080
      - 25482:25482