#!/usr/bin/with-contenv ash

addgroup -S omnidb
adduser -S omnidb -G omnidb
chown -R omnidb:omnidb /opt/OmniDB-*
chown -R omnidb:omnidb /etc/omnidb

su omnidb -s /bin/ash -c\
 "python3 /opt/OmniDB-2.17.0/OmniDB/omnidb-server.py --host=0.0.0.0 --port=8080 -d /etc/omnidb &"
sleep 3

#add super user
su omnidb -s /bin/ash -c\
 "python3 /opt/OmniDB-2.17.0/OmniDB/omnidb-config.py -s $OMNIDB_USER $OMNIDB_PASS -d /etc/omnidb/"

#remove default admin user
if [ "$OMNIDB_USER" != "admin" ]; then
    su omnidb -s /bin/ash -c\
     "python3 /opt/OmniDB-2.17.0/OmniDB/omnidb-config.py -x admin -d /etc/omnidb/"
fi

#creating connection
su omnidb -s /bin/ash -c\
 "python3 /opt/OmniDB-2.17.0/OmniDB/omnidb-config.py -c $OMNIDB_USER $DB_TECH $DB_HOST $DB_PORT $DB_NAME $DB_USER -d /etc/omnidb/"

kill $( ps aux | grep omnidb | grep python3 | cut -d ' '  -f3 )


echo 0 > /tmp/omnidb

